spring.application.name: hotel-manage
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/mydb4
spring.datasource.username: root
spring.datasource.password: 123456
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.yfc.hotel.manage.domain
  mapper-locations: classpath*:com/yfc/hotel/manage/dao/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
